const {test}=require('node:test');const assert=require('node:assert/strict');
const {decision,assess,businessHours,canonical,summarize,createRecovery}=require('./recovery');
const now=new Date('2026-10-03T19:00:00Z'),base={phone:'whatsapp:+525500000001',mode:'aura',lastInbound:'2026-10-03T18:00:00Z',commercial:{classification:'prospect'},recovery:{status:'queued',dueAt:'2026-10-03T18:00:00Z',enrolledAt:'2026-10-03T17:00:00Z',origin:'automatic'}};
test('Sólo horario de México; sábado termina a las 15 y domingo cerrado',()=>{assert.equal(businessHours(now),true);assert.equal(businessHours(new Date('2026-10-03T21:00:00Z')),false);assert.equal(businessHours(new Date('2026-10-04T19:00:00Z')),false);assert.equal(canonical('whatsapp:+5215512345678'),canonical('whatsapp:+525512345678'));});
test('No envía después de 24 horas sin consentimiento y aprobación',()=>{const row={...base,lastInbound:'2026-09-30T18:00:00Z'};assert.equal(decision(row,now,{enabled:true},{sid:'HXx',status:'approved'}),'needs_consent');row.commercial={...row.commercial,whatsappFollowupConsent:{evidence:'Mensaje del paciente'}};assert.equal(decision(row,now,{enabled:true},{}),'needs_template');assert.equal(decision(row,now,{enabled:true},{sid:'HXx',status:'approved'}),'template');});
test('Ventana abierta, pausa, hora acordada, humano, confirmado y rechazo',()=>{assert.equal(decision(base,now,{enabled:true},{}),'session');assert.equal(decision(base,now,{enabled:false},{}),'paused');assert.equal(decision({...base,recovery:{...base.recovery,dueAt:'2026-10-05T17:00:00Z'}},now,{enabled:true},{}),'waiting');assert.equal(decision({...base,mode:'human'},now,{enabled:true},{}),'human');assert.equal(decision({...base,commercial:{...base.commercial,appointment:{status:'confirmed'}}},now,{enabled:true},{}),'confirmed');assert.equal(decision({...base,commercial:{...base.commercial,doNotContact:true}},now,{enabled:true},{}),'excluded');});
test('Evalúa sólo mensajes del paciente y excluye proveedores, pruebas, distancia y rechazo',()=>{for(const body of ['Mensaje de prueba','Soy proveedor','Me keda lejos','No gracias','Ya tengo cita'])assert.equal(assess(base,[{from:base.phone,body,dateCreated:now,sid:'SM1'}],'+525566777788').eligible,false);assert.equal(assess(base,[{from:base.phone,body:'Quiero información sobre implantes',dateCreated:now,sid:'SM2'}],'+525566777788').eligible,true);assert.equal(assess(base,[{from:'doctor',body:'Quiero una cita',dateCreated:now}],'+525566777788').eligible,false);});
test('No confunde enviado con entregado, respuesta, cita ni dinero',()=>{let m=summarize([{...base,name:'Caso',recovery:{...base.recovery,sid:'SMx',status:'sent',deliveryStatus:'sent'}}]);assert.equal(m.sent,1);assert.equal(m.delivered,0);assert.equal(m.responded,0);assert.equal(m.confirmedAfterResponse,0);assert.equal(m.collectedMXN,0);});
function fake(){let data=structuredClone(base),sent=0;const records=new Map();const docs=name=>({fetch:async()=>{if(name==='thera-recovery-settings-v1')return {data:{enabled:true}};if(!records.has(name))throw {status:404};return records.get(name);},update:async({data})=>{records.set(name,{data});return {data};}});docs.create=async({uniqueName,data})=>{if(records.has(uniqueName))throw {status:409};records.set(uniqueName,{data});return {data};};const client={messages:Object.assign(sid=>({fetch:async()=>({sid,status:'delivered'})}),{create:async()=>{sent++;return {sid:'SM123',status:'sent'};}})};const store={documents:docs,list:async()=>[data],ensure:async()=>({data}),mutate:async(p,fn)=>data=fn(data)};return {store,client,count:()=>sent,data:()=>data,set:d=>data=d};}
test('Registro duradero evita repetir incluso tras reiniciar el proceso',async()=>{const f=fake(),args={...f,from:'whatsapp:+525500000009',env:{INBOX_PUBLIC_URL:'https://example.test'},push:{send:async()=>{}},locked:async(p,fn)=>fn()};const first=createRecovery(args);await first.tick(now);first.stop();assert.equal(f.count(),1);f.set({...f.data(),recovery:{...base.recovery}});const restarted=createRecovery(args);await restarted.tick(now);restarted.stop();assert.equal(f.count(),1);assert.equal(f.data().recovery.status,'uncertain');});
test('Twilio no confirma: no reintenta mensajes que pudieron cobrarse',async()=>{const f=fake();let attempts=0;f.client.messages.create=async()=>{attempts++;throw new Error('timeout');};const r=createRecovery({...f,from:'whatsapp:+525500000009',env:{INBOX_PUBLIC_URL:'https://example.test'},push:{send:async()=>{}},locked:async(p,fn)=>fn()});await r.tick(now);await r.tick(now);r.stop();assert.equal(attempts,1);assert.equal(f.data().recovery.status,'uncertain');});
test('Comunica sólo cita futura comprobada, una vez, sin contarla como recuperación',async()=>{const f=fake();f.set({...base,commercial:{classification:'prospect',appointment:{status:'confirmed',at:'2026-10-05T17:00:00Z',evidence:'Agenda verificada',confirmedBy:'Dr. Jaime Reyes'}}});const r=createRecovery({...f,from:'whatsapp:+525500000009',env:{INBOX_PUBLIC_URL:'https://example.test'},push:{send:async()=>{}},locked:async(p,fn)=>fn()});await r.tick(now);await r.tick(now);r.stop();assert.equal(f.count(),1);assert.equal(f.data().confirmationNotice.appointmentAt,'2026-10-05T17:00:00Z');assert.equal(summarize([f.data()]).sent,0);assert.equal(summarize([f.data()]).confirmedAfterResponse,0);});
test('Una cita declarada sin evidencia o una cita pasada no genera confirmación',async()=>{for(const appointment of [{status:'confirmed',at:'2026-10-05T17:00:00Z'},{status:'confirmed',at:'2026-10-02T17:00:00Z',evidence:'Agenda',confirmedBy:'Doctor'}]){const f=fake();f.set({...base,commercial:{classification:'prospect',appointment}});const r=createRecovery({...f,from:'whatsapp:+525500000009',env:{INBOX_PUBLIC_URL:'https://example.test'},push:{send:async()=>{}},locked:async(p,fn)=>fn()});await r.tick(now);r.stop();assert.equal(f.count(),0);}});
test('El NO al mensaje de recuperación detiene el seguimiento',()=>{const w=require('./attention-workflow'),c=w.updateInbound({classification:'prospect'},{MessageSid:'SMnew',Body:'NO'},[{role:'assistant',content:require('./recovery').BODY}],now);assert.equal(c.doNotContact,true);});
test('Aura registra permiso específico; rechazarlo conserva cita pendiente sin seguimiento',()=>{const w=require('./attention-workflow'),c={classification:'prospect',awaiting:'whatsapp_followup_permission',appointment:{status:'pending'}},history=[{role:'assistant',content:'¿Autorizas que Aura te dé seguimiento por este WhatsApp hasta confirmar la cita?'}];assert.equal(w.updateInbound(c,{MessageSid:'SMpermission',Body:'Sí'},history,now).whatsappFollowupConsent.evidence,'SMpermission');const rejected=w.updateInbound(c,{MessageSid:'SMno',Body:'No'},history,now);assert.equal(rejected.doNotContact,true);assert.equal(rejected.appointment.status,'pending');});
test('Un sí a otra pregunta no autoriza seguimiento propuesto previamente',()=>{const w=require('./attention-workflow'),c={classification:'prospect',followUp:{status:'proposed'}};const updated=w.updateInbound(c,{MessageSid:'SMother',Body:'Sí'},[{role:'assistant',content:'¿Puedes acudir a Interlomas?'}],now);assert.equal(updated.whatsappFollowupConsent,undefined);assert.equal(updated.followUp.status,'proposed');});
test('Prepara plantilla de WhatsApp como marketing una vez, sin crear anuncios',async()=>{let content,approval,created=0,submitted=0;const contents=()=>({approvalFetch:()=>({fetch:async()=>{if(!approval)throw {status:404};return approval;}}),approvalCreate:{create:async input=>{assert.equal(input.category,'MARKETING');submitted++;approval={whatsapp:{status:'pending'}};}}});contents.list=async()=>content?[content]:[];contents.create=async input=>{created++;assert.equal(input.types['twilio/text'].body,require('./recovery').BODY);content={sid:'HXmock',friendlyName:input.friendly_name,types:input.types};return content;};const client={content:{v1:{contents}}},prepare=require('./recovery-template').prepare;assert.equal(await prepare(client,require('./recovery').BODY),'HXmock');assert.equal(await prepare(client,require('./recovery').BODY),'HXmock');assert.equal(created,1);assert.equal(submitted,1);});

test('Recuperación conserva datos declarados aunque ya tenga ficha inicial',()=>{const w=require('./attention-workflow'),c=w.updateInbound(w.initial(),{MessageSid:'SMreturn',Body:'Sí'},[{role:'user',content:'Me llamo Kathia Strevel'},{role:'user',content:'Necesito un diente'},{role:'assistant',content:'¿Quieres agendar una valoración?'}],now);assert.equal(c.patientName,'Kathia Strevel');assert.equal(c.teeth,1);assert.equal(c.appointment.status,'pending');assert.equal(c.whatsappFollowupConsent,undefined);});
